languageCode = "fr-fr"
baseurl = "http://auditor-rat-40867.netlify.com/"
title = "Mon site perso"

theme="amp"
paginate = 10
copyright = "© 2016 Copyright Text"
canonifyurls = true
googleAnalytics = "Your Tracking Id" # optional

# optional
[[menu.header]]
  name = "ABOUT"
  weight = 1
  url = "/about/"
[[menu.header]]
  name = "Tag"
  weight = 2
  url = "/tags/"
[[menu.header]]
  name = "Category"
  weight = 3
  url = "/categories/"

# optional
[social]
  twitter = "Your Twitter Name"
  github = "Your Github Name"
  facebook = "Your facebook Name"
  gplus = "Your Google+ profile name"
  linkedin = "Your LinkedIn Name"